// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "2a0c1cec-24c3-4716-9c1e-598e687c54dd";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onMatrixDisplayChange();
void onLEDChange();

String matrixDisplay;
int personConfidence;
bool LED;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(matrixDisplay, READWRITE, ON_CHANGE, onMatrixDisplayChange);
  ArduinoCloud.addProperty(personConfidence, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(LED, READWRITE, ON_CHANGE, onLEDChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
